In [1]:
print("all is okay")

all is okay


In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [3]:
documents =["people watch movie", 
            "people watch cricket", 
            "people like movie",
            "people like cricket"
            ]

In [4]:
tokens = [sentence.lower().split() for sentence in documents]
print(tokens)


[['people', 'watch', 'movie'], ['people', 'watch', 'cricket'], ['people', 'like', 'movie'], ['people', 'like', 'cricket']]


In [5]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

conver the tokens into 2D word matrix

In [6]:
all_words = [[word] for sentence in tokens for word in sentence]

In [7]:
all_words

[['people'],
 ['watch'],
 ['movie'],
 ['people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['like'],
 ['movie'],
 ['people'],
 ['like'],
 ['cricket']]

creating object for OHE

OneHotEncoder is a predefined class 

In [8]:
encoder = OneHotEncoder(sparse_output=False)

In [9]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [10]:
encoder.categories_

[array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)]

In [11]:
print("Vocabulary:",encoder.categories_[0])

Vocabulary: ['cricket' 'like' 'movie' 'people' 'watch']


In [12]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

onvert tokens into vectors using encoder

In [13]:
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print( encoded_sentence)


Sentence: ['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

Sentence: ['people', 'like', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


ANnother example for ONe HOt Encoder

In [43]:
documents =["The input to this transformer should be an array-like of integers or strings", 
            "denoting the values taken on by categorical (discrete) features",
             " The features are encoded using a one-hot (aka ‘one-of-K’ or ‘dummy’) encoding scheme",
             "This creates a binary column for each category and returns a sparse matrix or dense array"]

In [44]:
documents

['The input to this transformer should be an array-like of integers or strings',
 'denoting the values taken on by categorical (discrete) features',
 ' The features are encoded using a one-hot (aka ‘one-of-K’ or ‘dummy’) encoding scheme',
 'This creates a binary column for each category and returns a sparse matrix or dense array']

tokens = [sentence.lower().split() for sentence in documents]
print(tokens)

In [45]:
tokens = [sentence.lower().split() for sentence in documents]

In [46]:
tokens

[['the',
  'input',
  'to',
  'this',
  'transformer',
  'should',
  'be',
  'an',
  'array-like',
  'of',
  'integers',
  'or',
  'strings'],
 ['denoting',
  'the',
  'values',
  'taken',
  'on',
  'by',
  'categorical',
  '(discrete)',
  'features'],
 ['the',
  'features',
  'are',
  'encoded',
  'using',
  'a',
  'one-hot',
  '(aka',
  '‘one-of-k’',
  'or',
  '‘dummy’)',
  'encoding',
  'scheme'],
 ['this',
  'creates',
  'a',
  'binary',
  'column',
  'for',
  'each',
  'category',
  'and',
  'returns',
  'a',
  'sparse',
  'matrix',
  'or',
  'dense',
  'array']]

In [47]:
all_words = [[word] for sentence in tokens for word in sentence]

In [49]:
all_words

[['the'],
 ['input'],
 ['to'],
 ['this'],
 ['transformer'],
 ['should'],
 ['be'],
 ['an'],
 ['array-like'],
 ['of'],
 ['integers'],
 ['or'],
 ['strings'],
 ['denoting'],
 ['the'],
 ['values'],
 ['taken'],
 ['on'],
 ['by'],
 ['categorical'],
 ['(discrete)'],
 ['features'],
 ['the'],
 ['features'],
 ['are'],
 ['encoded'],
 ['using'],
 ['a'],
 ['one-hot'],
 ['(aka'],
 ['‘one-of-k’'],
 ['or'],
 ['‘dummy’)'],
 ['encoding'],
 ['scheme'],
 ['this'],
 ['creates'],
 ['a'],
 ['binary'],
 ['column'],
 ['for'],
 ['each'],
 ['category'],
 ['and'],
 ['returns'],
 ['a'],
 ['sparse'],
 ['matrix'],
 ['or'],
 ['dense'],
 ['array']]

In [51]:
enc = OneHotEncoder(sparse_output=False)

In [54]:
x_encoded = enc.fit(all_words)

In [55]:
x_encoded

OneHotEncoder(sparse_output=False)

In [56]:
x_encoded.categories_

[array(['(aka', '(discrete)', 'a', 'an', 'and', 'are', 'array',
        'array-like', 'be', 'binary', 'by', 'categorical', 'category',
        'column', 'creates', 'denoting', 'dense', 'each', 'encoded',
        'encoding', 'features', 'for', 'input', 'integers', 'matrix', 'of',
        'on', 'one-hot', 'or', 'returns', 'scheme', 'should', 'sparse',
        'strings', 'taken', 'the', 'this', 'to', 'transformer', 'using',
        'values', '‘dummy’)', '‘one-of-k’'], dtype=object)]

In [57]:
x_encoded.categories_[0]

array(['(aka', '(discrete)', 'a', 'an', 'and', 'are', 'array',
       'array-like', 'be', 'binary', 'by', 'categorical', 'category',
       'column', 'creates', 'denoting', 'dense', 'each', 'encoded',
       'encoding', 'features', 'for', 'input', 'integers', 'matrix', 'of',
       'on', 'one-hot', 'or', 'returns', 'scheme', 'should', 'sparse',
       'strings', 'taken', 'the', 'this', 'to', 'transformer', 'using',
       'values', '‘dummy’)', '‘one-of-k’'], dtype=object)

In [58]:
print("Vocabulary", x_encoded.categories_[0])

Vocabulary ['(aka' '(discrete)' 'a' 'an' 'and' 'are' 'array' 'array-like' 'be'
 'binary' 'by' 'categorical' 'category' 'column' 'creates' 'denoting'
 'dense' 'each' 'encoded' 'encoding' 'features' 'for' 'input' 'integers'
 'matrix' 'of' 'on' 'one-hot' 'or' 'returns' 'scheme' 'should' 'sparse'
 'strings' 'taken' 'the' 'this' 'to' 'transformer' 'using' 'values'
 '‘dummy’)' '‘one-of-k’']


In [63]:
y = x_encoded.transform([[word] for word in sentence])

In [64]:
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0.,

In [59]:
for sentence in tokens:
    encoded_sentence = x_encoded.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print( encoded_sentence)


Sentence: ['the', 'input', 'to', 'this', 'transformer', 'should', 'be', 'an', 'array-like', 'of', 'integers', 'or', 'strings']
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

BOW - Bag of Worrds 

Convert a collection of text documents to a matrix of token counts.

In [14]:
from sklearn.feature_extraction.text import CountVectorizer


In [15]:

documents =["people watch movie and watch movie again",
"people watch cricket and watch cricket",
"people like movie and like movie a lot",
"people like cricket"]

In [16]:
documents

['people watch movie and watch movie again',
 'people watch cricket and watch cricket',
 'people like movie and like movie a lot',
 'people like cricket']

AIM: convert data into NUmber

In [17]:
bow = CountVectorizer()

In [18]:
bow

CountVectorizer()

In [19]:
bow_matrix_fit = bow.fit(documents)

In [20]:
bow_matrix_fit

CountVectorizer()

AttributeError: 'CountVectorizer' object has no attribute 'toarray'

In [21]:
bow_matrix = bow.fit_transform(documents)

In [22]:
bow_matrix

<4x8 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [24]:
print("BOW Matrix:\n",bow_matrix.toarray())

BOW Matrix:
 [[1 1 0 0 0 2 1 2]
 [0 1 2 0 0 0 1 2]
 [0 1 0 2 1 2 1 0]
 [0 0 1 1 0 0 1 0]]


to get the vocabulary

In [23]:
bow.get_feature_names_out()

array(['again', 'and', 'cricket', 'like', 'lot', 'movie', 'people',
       'watch'], dtype=object)

In [24]:
print("vocabulary:", bow.get_feature_names_out())

vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']


convert ito BOW(Bag of Words)

In [25]:
document = ["divesh is a good mentor he teaches us very well he teaches the project. "]

In [26]:
BOW = CountVectorizer()

In [27]:
BOW

CountVectorizer()

In [28]:
bow_matrix1 = BOW.fit_transform(document)

In [29]:
bow_matrix1

<1x11 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [30]:
print("BOW Matrix:\n",bow_matrix1.toarray())

BOW Matrix:
 [[1 1 2 1 1 1 2 1 1 1 1]]


In [31]:
BOW.get_feature_names_out()

array(['divesh', 'good', 'he', 'is', 'mentor', 'project', 'teaches',
       'the', 'us', 'very', 'well'], dtype=object)

In [33]:
print("vocabulary:",BOW.get_feature_names_out())

vocabulary: ['divesh' 'good' 'he' 'is' 'mentor' 'project' 'teaches' 'the' 'us' 'very'
 'well']
